### ISSUE TITLE
Notifications didn't hide out when no animate.css linked and modalAnimation is set

### ISSUE THREAD

**Issue by dawidcieszynski** [ssbeefeater/ssi-modal#1]
There should be linked animate.css if you want to use animations (and set modalAnimation). If animate.css is not linked, notifications stays forever. If modalAnimation is not set, notifications works correctly.

Also please add info about animate.css to documentation :)

**Comment by ssbeefeater** [comment]
Unfortunatly to check if an animation exists is very expensive operation and i think is unnecessary.In the scenario that the browser doesn't support css animations, it will change to fade in/out. Now about the documentation you are right, i didn't mention it and can be tricky but now i fixed it. Thanks for that!
